collections:
  authors:
    output: true

title: Official website of Zakary Draper
tagline: A website and blog showcasing psychology research
description: Official website of Zakary Draper, Psychological Science PhD student and research at The University of British Columbia—Okanagan
url: http://zakarydraper.github.io
version: "1.0.0"
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
